import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./ui/Header/Header";

import { isLoggedIn } from "./lib/session";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const isAuthenticated = await isLoggedIn();

  return (
    <html lang="en">
      <body
        className={`px-7 md:px-[unset] max-w-3xl mx-auto ${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        {isAuthenticated &&
          <div className="text-2xl gap-4">
            <Header />
          </div>
        }
        {children}
      </body>
    </html>
  );
}
